-- SWYNEX Internship - Task 2
-- NYC Taxi Exploratory Data Analysis
-- Overall Statistics

-- 1. Total number of cleaned trips
SELECT
    COUNT(*) AS TOTAL_TRIPS
FROM NYC_TAXI_DQ.RAW.YELLOW_TAXI_CLEANED;


-- 2. Trip distance statistics
SELECT
    MIN(TRIP_DISTANCE) AS MIN_TRIP_DISTANCE,
    MAX(TRIP_DISTANCE) AS MAX_TRIP_DISTANCE,
    AVG(TRIP_DISTANCE) AS AVG_TRIP_DISTANCE,
    MEDIAN(TRIP_DISTANCE) AS MEDIAN_TRIP_DISTANCE
FROM NYC_TAXI_DQ.RAW.YELLOW_TAXI_CLEANED;


-- 3. Trip duration statistics
SELECT
    MIN(DATEDIFF('minute', TPEP_PICKUP_DATETIME, TPEP_DROPOFF_DATETIME)) AS MIN_DURATION_MINUTES,
    MAX(DATEDIFF('minute', TPEP_PICKUP_DATETIME, TPEP_DROPOFF_DATETIME)) AS MAX_DURATION_MINUTES,
    AVG(DATEDIFF('minute', TPEP_PICKUP_DATETIME, TPEP_DROPOFF_DATETIME)) AS AVG_DURATION_MINUTES,
    MEDIAN(DATEDIFF('minute', TPEP_PICKUP_DATETIME, TPEP_DROPOFF_DATETIME)) AS MEDIAN_DURATION_MINUTES
FROM NYC_TAXI_DQ.RAW.YELLOW_TAXI_CLEANED;


-- 4. Fare and total amount statistics
SELECT
    MIN(FARE_AMOUNT) AS MIN_FARE_AMOUNT,
    MAX(FARE_AMOUNT) AS MAX_FARE_AMOUNT,
    AVG(FARE_AMOUNT) AS AVG_FARE_AMOUNT,
    MEDIAN(FARE_AMOUNT) AS MEDIAN_FARE_AMOUNT,
    MIN(TOTAL_AMOUNT) AS MIN_TOTAL_AMOUNT,
    MAX(TOTAL_AMOUNT) AS MAX_TOTAL_AMOUNT,
    AVG(TOTAL_AMOUNT) AS AVG_TOTAL_AMOUNT,
    MEDIAN(TOTAL_AMOUNT) AS MEDIAN_TOTAL_AMOUNT
FROM NYC_TAXI_DQ.RAW.YELLOW_TAXI_CLEANED;