-- SWYNEX Internship - Task 2
-- NYC Taxi Exploratory Data Analysis
-- Time Analysis


-- 1. Number of trips by pickup date
SELECT
    CAST(TPEP_PICKUP_DATETIME AS DATE) AS PICKUP_DATE,
    COUNT(*) AS TOTAL_TRIPS
FROM NYC_TAXI_DQ.RAW.YELLOW_TAXI_CLEANED
WHERE TPEP_PICKUP_DATETIME >= '2026-01-01'
  AND TPEP_PICKUP_DATETIME < '2026-02-01'
GROUP BY CAST(TPEP_PICKUP_DATETIME AS DATE)
ORDER BY PICKUP_DATE;


-- 2. Average trips per day by weekday
SELECT
    DAYNAME(TPEP_PICKUP_DATETIME) AS WEEKDAY,
    COUNT(*) AS TOTAL_TRIPS,
    COUNT(*) / COUNT(DISTINCT CAST(TPEP_PICKUP_DATETIME AS DATE)) AS AVG_TRIPS_PER_DAY
FROM NYC_TAXI_DQ.RAW.YELLOW_TAXI_CLEANED
WHERE TPEP_PICKUP_DATETIME >= '2026-01-01'
  AND TPEP_PICKUP_DATETIME < '2026-02-01'
GROUP BY DAYNAME(TPEP_PICKUP_DATETIME)
ORDER BY AVG_TRIPS_PER_DAY DESC;


-- 3. Number of trips by pickup hour
SELECT
    HOUR(TPEP_PICKUP_DATETIME) AS PICKUP_HOUR,
    COUNT(*) AS TOTAL_TRIPS
FROM NYC_TAXI_DQ.RAW.YELLOW_TAXI_CLEANED
WHERE TPEP_PICKUP_DATETIME >= '2026-01-01'
  AND TPEP_PICKUP_DATETIME < '2026-02-01'
GROUP BY HOUR(TPEP_PICKUP_DATETIME)
ORDER BY PICKUP_HOUR;