-- SWYNEX Internship - Task 2
-- NYC Taxi Exploratory Data Analysis
-- Location Analysis


-- 1. Top pickup zones
SELECT
    L.ZONE AS PICKUP_ZONE,
    COUNT(*) AS TOTAL_TRIPS
FROM NYC_TAXI_DQ.RAW.YELLOW_TAXI_CLEANED T
JOIN NYC_TAXI_DQ.LOOKUP.TAXI_ZONE_LOOKUP L
    ON T.PULOCATIONID = L.LOCATIONID
GROUP BY L.ZONE
ORDER BY TOTAL_TRIPS DESC
LIMIT 10;

-- 2. Top drop-off zones
SELECT
    L.ZONE AS DROPOFF_ZONE,
    COUNT(*) AS TOTAL_TRIPS
FROM NYC_TAXI_DQ.RAW.YELLOW_TAXI_CLEANED T
JOIN NYC_TAXI_DQ.LOOKUP.TAXI_ZONE_LOOKUP L
    ON T.DOLOCATIONID = L.LOCATIONID
GROUP BY L.ZONE
ORDER BY TOTAL_TRIPS DESC
LIMIT 10;

-- 3. Top pickup and drop-off routes
SELECT
    P.ZONE AS PICKUP_ZONE,
    D.ZONE AS DROPOFF_ZONE,
    COUNT(*) AS TOTAL_TRIPS
FROM NYC_TAXI_DQ.RAW.YELLOW_TAXI_CLEANED T
JOIN NYC_TAXI_DQ.LOOKUP.TAXI_ZONE_LOOKUP P
    ON T.PULOCATIONID = P.LOCATIONID
JOIN NYC_TAXI_DQ.LOOKUP.TAXI_ZONE_LOOKUP D
    ON T.DOLOCATIONID = D.LOCATIONID
GROUP BY
    P.ZONE,
    D.ZONE
ORDER BY TOTAL_TRIPS DESC
LIMIT 10;