-- SWYNEX Internship - Task 2
-- NYC Taxi Exploratory Data Analysis
-- Anomaly Analysis


-- 1. Trips with duration above 300 minutes
SELECT
    COUNT(*) AS TRIPS_OVER_300_MINUTES,
    SUM(CASE WHEN TRIP_DISTANCE = 0 THEN 1 ELSE 0 END) AS ZERO_DISTANCE_TRIPS,
    SUM(CASE WHEN TRIP_DISTANCE > 0 THEN 1 ELSE 0 END) AS POSITIVE_DISTANCE_TRIPS,
    AVG(TRIP_DISTANCE) AS AVG_TRIP_DISTANCE,
    MEDIAN(TRIP_DISTANCE) AS MEDIAN_TRIP_DISTANCE,
    AVG(TOTAL_AMOUNT) AS AVG_TOTAL_AMOUNT,
    MEDIAN(TOTAL_AMOUNT) AS MEDIAN_TOTAL_AMOUNT
FROM NYC_TAXI_DQ.RAW.YELLOW_TAXI_CLEANED
WHERE DATEDIFF('minute', TPEP_PICKUP_DATETIME, TPEP_DROPOFF_DATETIME) > 300;

-- 2. Detailed review of trips with duration above 300 minutes
SELECT
    TPEP_PICKUP_DATETIME,
    TPEP_DROPOFF_DATETIME,
    DATEDIFF('minute', TPEP_PICKUP_DATETIME, TPEP_DROPOFF_DATETIME) AS DURATION_MINUTES,
    TRIP_DISTANCE,
    FARE_AMOUNT,
    TOTAL_AMOUNT,
    PAYMENT_TYPE
FROM NYC_TAXI_DQ.RAW.YELLOW_TAXI_CLEANED
WHERE DATEDIFF('minute', TPEP_PICKUP_DATETIME, TPEP_DROPOFF_DATETIME) > 300
ORDER BY DURATION_MINUTES DESC
LIMIT 100;